export { ID_PREFIXES, newId, isIdOfKind, type IdKind } from './ids.js';
export {
  CHAPTER_KINDS,
  ENTITY_TYPES,
  ENTITY_STATUSES,
  SEGMENT_KINDS,
  EMOTION_TYPES,
  PARSE_PASSES,
  PARSE_RUN_STATUSES,
  UNKNOWN_SPEAKER_SURFACE,
  entityNames,
  isEntityType,
  type KnownEntity,
  type ChapterKind,
  type EntityType,
  type EntityStatus,
  type SegmentKind,
  type EmotionType,
  type ParsePass,
  type ParseRunStatus,
} from './domain.js';
export {
  type Span,
  isWellFormedSpan,
  spanContains,
  spanContainsOffset,
  spanAt,
  sliceSpan,
  findQuote,
  occurrences,
  complementSpans,
  sortSpans,
} from './text/span.js';
export { sha256Hex } from './text/hash.js';
export {
  IR_VERSION,
  ChapterIRSchema,
  SceneIRSchema,
  SegmentIRSchema,
  SpeakerIRSchema,
  EmotionIRSchema,
  EntityIRSchema,
  MentionIRSchema,
  ProvenanceIRSchema,
  type ChapterIR,
  type ChapterIRInput,
  type SceneIR,
  type SegmentIR,
  type SpeakerIR,
  type EmotionIR,
  type EntityIR,
  type MentionIR,
  type ProvenanceIR,
} from './ir/schema.js';
export { validateChapterIR, type ValidationCode, type ValidationError, type ValidationResult } from './ir/validate.js';
